### ISSUE TITLE
Is it possible to disable the screensaver part and just use the "browser"

### ISSUE THREAD

**Issue by marksev1** [enen92/script.screensaver.cocktail#4]
As the title says. Since for screensaver I already use Feedreader.

**Comment by enen92** [comment]
I don't get the issue. Can't the addon do what you need already? You are not obligated to use the addon as a screensaver. You can just start it from the program addon menu. 
Or do you mean an option to hide the start screensaver from the main menu?

**Comment by marksev1** [comment]
No I just thought it automatically overrides other screensavers :).

**Comment by marksev1** [comment]
Wait, why can't I find the addon in the menus of Kodi 17 even if its installed? I don't even find a "program addon menu" in Kodi 17?

**Comment by enen92** [comment]
you'll need to enter the addon list. I guess it will only show in the addon shortcuts (the "home" page) if you start it at least once

**Comment by marksev1** [comment]
I don't understand what you are saying, in the "home page" under the Addon menu item it is not displayed (youtube addon and others are displayed), there in "management of addons" element it is visible. (maybe its because my skin is slightly different than the default).
